apiVersion: v1
kind: Secret
metadata:
  name: quarkus-db-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  postgres-user: c2NfYWRtaW4=   # sc_admin
  postgres-password: c2NfYWRtaW4= # sc_admin